# Site Settings

title: Personal Blog
email: sauloaguiar89@gmail.com
author: Saulo Aguiar
url: http://sauloaguiar.github.io
github: sauloaguiar
linkedin: sauloaguiar
twitter: saulo_aguiar

# Build settings

markdown: kramdown
permalink: pretty

sass:
  sass_dir: assets/css
  style: :nested
  cache: false
